Title: Reading 2
Author: Dr. Glasbrenner
Author_Image: https://www.gravatar.com/avatar/49802fdfa5a0e63b3d932a5179d41c1e
Date: 2019-01-02 00:00
Tags: reading
Slug: reading02
Show_summary: false
Show_link: false

```{r setup, include = FALSE}
icon_link <- '<i class="fa fa-link"></i>&nbsp;'
icon_book <- '<i class="fa fa-book" data-fa-transform="grow-4"></i>&nbsp;'
```

`r icon_book` [Introduction to computational and data sciences supplemental book]{.h3}

`r icon_link` Book URL: <http://book.cds101.com>

**Chapter 2: GitHub**

*   Section 2.1 -- Getting started: <http://book.cds101.com/getting-started.html>

*   Section 2.2 -- Navigating the GitHub site: <http://book.cds101.com/navigating-the-github-site.html>

*   Section 2.3 -- Repositories: <http://book.cds101.com/repositories.html>

`r icon_book` [R for Data Science]{.h3}

`r icon_link` Book URL: <http://r4ds.had.co.nz>

**Chapter 27: R Markdown**

*   Full chapter: <http://r4ds.had.co.nz/r-markdown.html>

`r icon_book` [R Markdown: The Definitive Guide]{.h3}

`r icon_link` Book URL: <https://bookdown.org/yihui/rmarkdown>

**Chapter 2: Basics**

*   Introduction: <https://bookdown.org/yihui/rmarkdown/basics.html>

*   Section 2.2 -- Compile an R Markdown document: <https://bookdown.org/yihui/rmarkdown/compile.html>

*   Section 2.5 -- Markdown syntax: <https://bookdown.org/yihui/rmarkdown/markdown-syntax.html>

`r icon_book` [Introduction to Data Science: Data Analysis and Prediction Algorithms with R]{.h3}

`r icon_link` Book URL: <https://rafalab.github.io/dsbook/>

**Selections from chapters 2, 39, and 40**

*   Section 2.4.1 -- RStudio: The panes: <https://rafalab.github.io/dsbook/getting-started.html#the-panes>

*   Section 2.4.2 -- RStudio: Key bindings: <https://rafalab.github.io/dsbook/getting-started.html#key-bindings>

*   Section 2.4.4 -- RStudio: Global options: <https://rafalab.github.io/dsbook/getting-started.html#changing-global-options>

*   Section 39.6 -- Using Git and GitHub in RStudio: <https://rafalab.github.io/dsbook/git.html#rstudio-git>

*   Sections 40.1 -- RStudio projects: <https://rafalab.github.io/dsbook/reproducible-projects-with-rstudio-and-r-markdown.html#rstudio-projects>
